name: Build

on:
  push:
    branches:
      - main
      - dev
      - release-*
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install deps
        run: pnpm install
      
      - name: Debug submodule
        run: |
          echo "Checking submodule status..."
          git submodule status
          echo "Listing lib directory..."
          ls -la lib/
          echo "Listing solidity-ibc-eureka directory..."
          ls -la lib/solidity-ibc-eureka/
          echo "Checking if interface file exists..."
          ls -la lib/solidity-ibc-eureka/contracts/interfaces/

      - name: Compile
        run: pnpm compile
